"""removed department_id from ingredient table

Revision ID: 1b680c82ac29
Revises: 93c6db9f576b
Create Date: 2019-11-16 17:08:27.040263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b680c82ac29'
down_revision = '93c6db9f576b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
