"""fix for instructions column

Revision ID: 6c5189c53b58
Revises: cac294423e88
Create Date: 2019-11-16 12:39:25.578242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5189c53b58'
down_revision = 'cac294423e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'instructions')
    # ### end Alembic commands ###
